// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "todo-20200205205558-hostingbucket-todo",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://todo-20200205205558-hostingbucket-todo.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:7a16d70f-4625-4324-8cc9-3e856ab4b093",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_doMpaXJdS",
    "aws_user_pools_web_client_id": "5livlb73pft18e5r011i8aumd6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://63gqsrxtebfepd7lyjv3kkllzq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
